name: CI

on:
  push:
    branches:
      - main
    paths:
      - "Kata 01/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    
    - name: Restore dependencies
      run: dotnet restore './Kata 01/Kata 01.sln'
    
    - name: Build
      run: dotnet build --no-restore './Kata 01/Kata 01.sln'
    
    - name: Test
      run: dotnet test --no-build --verbosity normal --logger trx --results-directory "./TestResults/Kata 01" "./Kata 01/Kata 01.sln"
    
    - name: Display test results
      uses: dorny/test-reporter@v1
      if: ${{ always() }}
      with:
        name: "Kata 01 tests"
        path: "./TestResults/Kata 01/*.trx"
        reporter: dotnet-trx
